[package]
name = "repovia_http"
version = "1.0.0"
authors = ["Ryan Bruno <ryanbruno506@gmail.com>"]
edition = "2021"

[dependencies]
repovia_executor = { path = "../repovia-executor" }
repovia_utils = { path = "../repovia-utils" }
http = "1.0"
log = "0.4"